src/Entity/Party.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use App\Repository\PartyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Slug;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use JetBrains\PhpStorm\Pure;

#[ORM\Entity(repositoryClass: PartyRepository::class)]
class Party
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'datetime')]
    private $date;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $headliner;

    #[ORM\Column(type: 'integer')]
    private $price;

    #[ORM\Column(type: 'string', length: 255)]
    #[Slug(fields: ['name'])]
    private $slug;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'integer')]
    private $votes = 0;

    #[ORM\OneToMany(mappedBy: 'party', targetEntity: Comment::class, fetch: 'EXTRA_LAZY')]
    #[ORM\OrderBy(['createdAt' => 'DESC'])]
    private $comments;

    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'parties')]
    private $tags;

    #[ORM\ManyToOne(targetEntity: Venue::class, inversedBy: 'parties')]
    private $venue;

    #[ORM\ManyToMany(targetEntity: SMPost::class, mappedBy: 'parties')]
    private $smPosts;

//    #[ORM\Column(type: 'datetime', nullable: true)]
//    private $postedAt;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
        $this->smPosts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getHeadliner(): ?string
    {
        return $this->headliner;
    }

    public function setHeadliner(?string $headliner): self
    {
        $this->headliner = $headliner;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getVotes(): int
    {
        return $this->votes;
    }

    #[Pure]
    public function getVotesString(): string
    {
        $prefix = $this->getVotes() >= 0 ? '+' : '-';

        return sprintf('%s %d', $prefix, abs($this->getVotes()));
    }

    public function setVotes(int $votes): self
    {
        $this->votes = $votes;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function getApprovedComments(): Collection
    {
        return $this->comments->matching(CommentRepository::createApprovedCriteria());
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setParty($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getParty() === $this) {
                $comment->setParty(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getVenue(): ?Venue
    {
        return $this->venue;
    }

    public function setVenue(?Venue $venue): self
    {
        $this->venue = $venue;

        return $this;
    }

    /**
     * @return Collection|SMPost[]
     */
    public function getSmPosts(): Collection
    {
        return $this->smPosts;
    }

    public function addSmPost(SMPost $smPost): self
    {
        if (!$this->smPosts->contains($smPost)) {
            $this->smPosts[] = $smPost;
            $smPost->addParty($this);
        }

        return $this;
    }

    public function removeSmPost(SMPost $smPost): self
    {
        if ($this->smPosts->removeElement($smPost)) {
            $smPost->removeParty($this);
        }

        return $this;
    }
}
 

src/Entity/Venue.php
<?php

namespace App\Entity;

use App\Repository\VenueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VenueRepository::class)]
class Venue
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'string', length: 255)]
    private $address;

    #[ORM\Column(type: 'string', length: 100)]
    private $genre;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $capacity;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\OneToMany(mappedBy: 'venue', targetEntity: Party::class)]
    private $parties;

    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'venues')]
    private $tags;

    public function __construct()
    {
        $this->parties = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(?int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Party[]
     */
    public function getParties(): Collection
    {
        return $this->parties;
    }

    public function addParty(Party $party): self
    {
        if (!$this->parties->contains($party)) {
            $this->parties[] = $party;
            $party->setVenue($this);
        }

        return $this;
    }

    public function removeParty(Party $party): self
    {
        if ($this->parties->removeElement($party)) {
            // set the owning side to null (unless already changed)
            if ($party->getVenue() === $this) {
                $party->setVenue(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }
}

src/Controller/VenueController.php
<?php

namespace App\Controller;

use App\Repository\VenueRepository;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class VenueController extends AbstractController
{
    #[Route('/venue', name: 'app_venue')]
    public function allVenues(VenueRepository $repository): Response
    {
        $queryBuilder = $repository->createDataQueryBuilder();

        $pagerFanta = new Pagerfanta(
            new QueryAdapter($queryBuilder)
        );

        $pagerFanta->setMaxPerPage(5);

        return $this->render('venue/venue.html.twig', [
            'pager' => $pagerFanta,
        ]);
    }
}

templates/venue/venue.html.twig
{% extends 'base.html.twig' %}

{% block title %}Venues!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Kyiv clubs and party venues</h1>

    <div class="row">
        {% for venue in pager %}
            <div class="col-12">
                <div style="box-shadow: 2px 3px 9px 4px rgba(0,0,0,0.04);">
                    <div class="q-container p-4">e
                        <div class="row">
                            <div class="col-2 text-center">
                                <img src="{{ asset('images/richie.png') }}" width="100" height="100" alt="Tisha avatar">
                                <div class="d-block mt-3 vote-arrows">
                                    <span>{{ party.votesString }} votes</span>
                                    <br>
                                    {% for partyTag in party.partyTags %}
                                        <span class="badge rounded-pill bg-light text-dark">{{ party.tag.name }}</span>
                                    {% endfor %}
                                    {#                                        <a class="vote-up" href="#"><i class="far fa-arrow-alt-circle-up"></i></a>#}
                                    {#                                        <a class="vote-down" href="#"><i class="far fa-arrow-alt-circle-down"></i></a>#}
                                </div>
                            </div>
                            <div class="col">
                                <a class="q-title" href="{{ path('app_party_view', { slug: party.slug }) }}"><h2>{{ party.name }}</h2></a>
                                <div class="q-display p-3">
                                    <i class="fa fa-quote-left mr-3"></i>
                                    <p class="d-inline">{{ party.description }}</p>
                                    <p class="pt-4"><strong>Kyiv Rave</strong></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a class="answer-link" href="{{ path('app_party_view', { slug: party.slug }) }}" style="color: #fff;">
                        <p class="q-display-response text-center p-3">
                            <i class="fa fa-magic magic-wand"></i> {{ party.approvedComments|length }} comments
                        </p>
                    </a>
                </div>
            </div>
        {% endfor %}

        {{ pagerfanta(pager) }}
    </div>
</div>
{% endblock %}