src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use http\Exception\InvalidArgumentException;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    use TimestampableEntity;

    public const STATUS_NEEDS_APPROVAL = 'needs_approval';
    public const STATUS_SPAM = 'spam';
    public const STATUS_APPROVED = 'approved';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\Column(type: 'integer')]
    private $votes = 0;

    #[ORM\ManyToOne(targetEntity: Party::class, inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private $party;

    #[ORM\Column(type: 'string', length: 255)]
    private $username;

    #[ORM\Column(type: 'string', length: 15)]
    private $status = self::STATUS_NEEDS_APPROVAL;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'comments')]
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getVotes(): int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): self
    {
        $this->votes = $votes;

        return $this;
    }

    public function getParty(): ?Party
    {
        return $this->party;
    }

    public function getPartyText(): string
    {
        if(!$this->getParty()) {
            return '';
        }

        return (string) $this->getParty()->getParty();
    }

    public function setParty(?Party $party): self
    {
        $this->party = $party;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        if (!in_array($status, [self::STATUS_NEEDS_APPROVAL, self::STATUS_SPAM, self::STATUS_APPROVED])) {
            throw new \InvalidArgumentException(sprintf('Invalid status "%s"', $status));
        }

        $this->status = $status;

        return $this;
    }

    public function isApproved(): bool
    {
        return $this->status === self::STATUS_APPROVED;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/CommentController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Repository\CommentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class CommentController extends AbstractController
{
    /**
     * @Route("/comments/{id}/vote", methods="POST", name="comment_vote")
     */
    public function commentVote(Comment $comment, LoggerInterface $logger, Request $request, EntityManagerInterface $entityManager)
    {
        $data = json_decode($request->getContent(), true);
        $direction = $data['direction'] ?? 'up';

        // use real logic here to save this to the database
        if ($direction === 'up') {
            $logger->info('Voting up!');
            $comment->setVotes($comment->getVotes() + 1);
        } else {
            $logger->info('Voting down!');
            $comment->setVotes($comment->getVotes() - 1);
        }

        $entityManager->flush();

        return $this->json(['votes' => $comment->getVotes()]);
    }

    #[Route('/comments/popular', name: 'app_popular_comments')]
    public function popularComments(CommentRepository $commentRepository, Request $request)
    {
        $comments = $commentRepository->findMostPopular(
            $request->query->get('q')
        );

        return $this->render('comment/popularComments.html.twig',[
            'comments' => $comments
        ]);
    }
}

templates/comment/_comment.html.twig
<li class="mb-4">
    {% if showParty|default(false) %}
    <a
        href="{{ path('app_party_view', {
            slug: comment.party.slug
        }) }}"
        class="mb-1 link-secondary"
        >
        <strong>Party:</strong>
        {{ comment.partyText|u.truncate(80, '...') }}
    </a>
    {% endif %}
    <div class="row">
        <div class="col-1">
            <img src="{{ asset('images/raver.png') }}" width="50" height="50" alt="Tisha avatar">
        </div>
        <div class="col-9">
            {{ comment.content }}
            <p>-- {{ comment.username }}</p>
        </div>
        <div class="col-2 text-end">
            <small>{{ comment.createdAt|ago }}</small>
            <div
                    class="vote-arrows"
                    {{ stimulus_controller('comment-vote', {
                        url: path('comment_vote', {
                            id: comment.id
                        })
                    }) }}
            >
                <button
                        class="vote-up btn btn-link"
                        name="direction"
                        value="up"
                        {{ stimulus_action('comment-vote', 'clickVote') }}
                ><i class="far fa-arrow-alt-circle-up"></i></button>
                <button
                        class="vote-down btn btn-link"
                        name="direction"
                        value="down"
                        {{ stimulus_action('comment-vote', 'clickVote') }}
                ><i class="far fa-arrow-alt-circle-down"></i></button>
                <span><span {{ stimulus_target('comment-vote', 'voteTotal') }}>{{ comment.votes }}</span></span>
            </div>
        </div>
    </div>
</li>

templates/comment/popularComments.html.twig
{% extends 'base.html.twig' %}

{% block title %}Popular Comments{% endblock %}

{% block body %}
    <div class="container my-md-4">
        <div class="d-flex justify-content-between">
            <h1>Most Popular Comments</h1>
        </div>

        <form action="{{ path('app_popular_comments') }}">
            <input
            type="search"
            name="q"
            value="{{ app.request.query.get('q') }}"
            class="form-control"
            placeholder="Search..."
            aria-label="Search"
            >
        </form>

        <ul class="list-unstyled"
            {% for comment in comments %}
                {{ include('comment/_comment.html.twig', {
                    showParty: true
                }) }}
            {% endfor %}
        >
        </ul>
    </div>
{% endblock %}